### ISSUE TITLE
Update notifications have an unrecognizable icon and "SnoreToast" as the title

### ISSUE THREAD

**Issue by jnm2** [zidoro/pomatez#367] opened 2023-05-10 14:02 UTC
**Describe the bug**

There's nothing in these toasts that tells me that Pomatez is the app that is prompting them. My reaction every time is "What is SnoreToast? Did I get unwanted software on my machine?"

![image](https://github.com/zidoro/pomatez/assets/8040367/2b1cc223-2c36-4f6a-a7fe-2597e384e1c5)

**To Reproduce**

1. Have a version of Pomatez installed that is not the latest
2. Make sure it is configured to start at Windows startup
3. Sign out and back into your Windows user account to trigger the update check
4. See two Windows notification toasts appear a little while after Pomatez starts, similar to the screenshot above.

**Expected behavior**
The icon in the toasts should be the Pomatez icon and the title in the toast should contain the name 'Pomatez.'

**Screenshots**
See description.

**Desktop (please complete the following information):**

- OS: Windows 11
- App Version: 1.2.2
- Installer Used: Windows installer

**Comment by roldanjr** [comment] 2023-05-14 12:06
Hi @jnm2, thanks for letting us know about this behavior. Unfortunately, I can't verify this behavior in Windows 11 at this moment, maybe @huangyinhaow and @sekwah41 can help us fix this issue if they have some time to look at this, otherwise, we'll just keep this bug ticket open until I am able to test it out in actual Windows 11 machine.

I tried to replicate it in Linux but it seems fine here. I can't test it also in MacOS since my current device is broken.

**Comment by jnm2** [comment] 2023-05-14 21:19
I found instructions at <https://github.com/mikaelbr/node-notifier#usage-windowstoaster> referencing "SnoreToast":

> The default behaviour is to have the underlying toaster applicaton as appID. This works as expected, but shows SnoreToast as text in the notification.
>
> With the Fall Creators Update, Notifications on Windows 10 will only work as expected if a valid appID is specified. Your appID must be exactly the same value that was registered during the installation of your app.

**Comment by sekwah41** [comment] 2023-05-20 15:26
So the issue is, the library returns a different object depending on the running OS, we need to either construct our own notifier if Windows is detected, or see if we can construct it with a valid appid via the library.

**Comment by jnm2** [comment] 2023-05-20 17:21
Wouldn't be surprised if the type definitions could be corrected to match whatever the JS usage pattern is. TS's type system is so powerful because that's it's whole goal.

**Comment by sekwah41** [comment] 2023-05-20 18:12
@jnm2 in the pr ive just merged the two types, it is possible

**Comment by sekwah41** [comment] 2023-05-20 18:13
<img width="293" alt="image" src="https://github.com/zidoro/pomatez/assets/3209834/3e2d82d3-607b-4bd0-b0f7-1fb79e838367">

**Comment by sekwah41** [comment] 2023-05-20 18:14
I still need to check things e.g. the portable mode one, and make sure the update logic works for the interaction. But its most of the way there

**Comment by sekwah41** [comment] 2023-08-16 11:08
I'm switching back to windows as my main OS for desktop at least due to other apps I'm developing so I'll pick this up later this week or next week to validate and fully fix.

**Comment by sekwah41** [comment] 2023-11-12 14:46
I believe this is fixed, and we also have a tauri version too now :)

**Closed by sekwah41** 2023-11-12 14:46 UTC
Labels: bug, good first issue
